// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBth9Kbp8BOUsGNey-YzQyWLwa3sWy9bzI',
    appId: '1:98316427790:web:d88381ae4ae4710c82925f',
    messagingSenderId: '98316427790',
    projectId: 'sawrify',
    authDomain: 'sawrify.firebaseapp.com',
    storageBucket: 'sawrify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEKLZxpfqMzNxCuUshLH4rGG_ZJKN7WAg',
    appId: '1:98316427790:android:919300eaa60ac79482925f',
    messagingSenderId: '98316427790',
    projectId: 'sawrify',
    storageBucket: 'sawrify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUUyo5vldhtPbaCVTJX8iLvr5idhCajmo',
    appId: '1:98316427790:ios:41d3446ba1e1931282925f',
    messagingSenderId: '98316427790',
    projectId: 'sawrify',
    storageBucket: 'sawrify.appspot.com',
    iosBundleId: 'com.example.sawtify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUUyo5vldhtPbaCVTJX8iLvr5idhCajmo',
    appId: '1:98316427790:ios:41d3446ba1e1931282925f',
    messagingSenderId: '98316427790',
    projectId: 'sawrify',
    storageBucket: 'sawrify.appspot.com',
    iosBundleId: 'com.example.sawtify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBth9Kbp8BOUsGNey-YzQyWLwa3sWy9bzI',
    appId: '1:98316427790:web:9f9fc970cb303e7a82925f',
    messagingSenderId: '98316427790',
    projectId: 'sawrify',
    authDomain: 'sawrify.firebaseapp.com',
    storageBucket: 'sawrify.appspot.com',
  );
}
